routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Match;
use App\Models\SliderModel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // $sliders= \File::allFiles(public_path('images'));
    $sliders=SliderModel::all();
    $matches = Match::all();
    return view('welcome', compact('sliders','matches'));
    
 
});


Auth::routes();


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('superAdmin','App\Http\Controllers\superAdminController');
Route::resource('match','App\Http\Controllers\MatchController');
Route::resource('slider','App\Http\Controllers\SliderController');

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
use File;
use Illuminate\Support\Storage\Facades;
use App\Models\SliderModel;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $sliders = SliderModel::all();
             
        return view('sliders.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $sliders=SliderModel::all();
        return view('sliders.create', compact('sliders'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $request->validate([            
                                
           
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
                  
        ]);  
        
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $image_name= time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            $image->move($destinationPath, $image_name);  

        }




        $slider = new SliderModel([            
                                
            
            'image_name'=>$image_name,
            'image_url'=>$destinationPath 
                         
            ]);        
        $slider->save(); 
        

        return redirect()->route('slider.index')->with('success','slider saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider=SliderModel::find($id);
        return view('sliders.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([ 
                   
           
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'                     
              
        ]);      
        
        $slider=SliderModel::find($id);
        File::delete(public_path("/images/").$slider->image_name);  
 
    
        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $image_name = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            $image->move($destinationPath, $image_name);


        $slider= SliderModel::find($id);        
                  
       
        $slider->image_name=$image_name;
               $slider->image_url=$destinationPath;
              
        $slider->save();        
        return redirect()->route('slider.index')->with('success', 'Slider saved');
    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $slider =SliderModel::find($id);
        
        File::delete(public_path("/images/").$slider->image_name);

        
       
        $slider->delete();
        return redirect()->route('slider.index')->with('success','Slider Deleted');
    }
}

resources/views/sliders/create.blade.php
@extends('home')
@section('homecontent')
<div class="row"> 
    <div class="col-sm-8 offset-sm-2">    
        <h3 class="display-4">Add Slider</h3>  
        <div>    
            @if ($errors->any())      
            <div class="alert alert-danger">        
                <ul>            
                @foreach ($errors->all() as $error)              
                <li>{{ $error }}</li>            
                @endforeach        
                </ul>      
            </div>
            <br />    
            @endif      
            <form enctype="multipart/form-data" method="post" action="{{ route('slider.store') }}">          
            @csrf 
            
            
            <div class="form-group d-flex flex-column">                  
                <label for="image">Image:</label>          
                <input type="file"  name="image"/>  
                       
            </div> 
                           
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('slider.index') }}" class="btn btn-primary">Cancel</a>  
                
            </form>  
        </div>
    </div>
</div>
@endsection

resources/views/sliders/edit.blade.php
@extends('home')
@section('homecontent')
<div class="row">    
    <div class="col-sm-8 offset-sm-2">        
        <h3 class="display-4">Update Slider</h3>        
        @if ($errors->any())        
        <div class="alert alert-danger">            
            <ul>                
            @foreach ($errors->all() as $error)                
            <li>{{ $error }}</li>                
            @endforeach            
            </ul>        
        </div>        
        <br />         
        @endif        
        <form enctype="multipart/form-data" method="post" action="{{ route('slider.update',$slider->id) }}">            
        @method('PATCH')             
        @csrf  

                  
             
            <div class="form-group d-flex flex-column">                
                <label for="image">Image:</label>                
                <input type="file"  name="image" value={{ $slider->image_name }}/>  
            </div>           
           

            <button type="submit" class="btn btn-success">Update</button>        
            <a href="{{ route('slider.index') }}" class="btn btn-primary">Cancel</a>                        
        </form>
    </div>
</div>
@endsection

resources/views/sliders/index.blade.php
@extends('home')
@section('homecontent')

<div class="row">
    <div class="col-sm-12">    
        <h1 class="display-4">Slider</h1>   
        <a href="{{ route('slider.create') }}" class="btn btn-primary">Add</a>  
        <table class="table table-striped">    
            <thead>        
            <tr>          
               
                <td> Image</td>
               

                <td colspan = 2>Actions</td>        
            </tr>    
            </thead>    
            <tbody>        
                @foreach($sliders as $slider)        
                    <tr>            
                                    
                       
                        <td>{{$slider->image_name}}
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#imageModal-{{$slider->id}}">
                            View
                            </button></td>
                        
                        
                        <td>                                      
                            <a href="{{ route('slider.edit',$slider->id)}}" class="btn btn-primary">Edit Slider</a>
                                                                  

                        </td> 
                        
                        
                        
                        <td>
                          <form action="{{ route('slider.destroy',$slider->id)}}" method="post">                  
                                @csrf                  
                               @method('DELETE')                  
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>    
                                      
                        </td> 
                        
          
                        
                    </tr>  



<div class="modal fade" id="imageModal-{{$slider->id}}" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"> 
      <img src="{{ URL::to('/') }}/images/{{$slider->image_name}}" width="100%">  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>         





                @endforeach    
            </tbody>  
        </table>
    <div>
</div>@endsection