routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Match;
use App\Models\SliderModel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // $sliders= \File::allFiles(public_path('images'));
    $sliders=SliderModel::all();
    $matches = Match::all();
    return view('welcome', compact('sliders','matches'));
    
 
});


Auth::routes();


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('superAdmin','App\Http\Controllers\superAdminController');
Route::resource('match','App\Http\Controllers\MatchController');
Route::resource('slider','App\Http\Controllers\SliderController');

app/Models/SuperAdmin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class superAdmin extends Model
{
    use HasFactory;
    protected $fillable = [
        'playerName',
        'countryName'
       
    ];
}

app/Http/Controllers/superAdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SuperAdmin;

class superAdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $superAdmins = SuperAdmin::all();
             
        return view('superAdmin.index', compact('superAdmins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $superAdmins=SuperAdmin::all();
        return view('superAdmin.create', compact('superAdmins'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        if ($request->user()->cannot('create', SuperAdmin::class)) {
            abort(403);
        }

        $request->validate([
            'playerName',
            'countryName'
        ]);
        $superAdmin=new SuperAdmin([
            'playerName'=>$request->get('playerName'),
            'countryName'=>$request->get('countryName')

        ]);
        $superAdmin->save();
        return redirect()->route('superAdmin.index')->with('success','SuperAdmin saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $superAdmin=SuperAdmin::find($id);
        return view('SuperAdmin.edit', compact('superAdmin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        if ($request->user()->cannot('update', SuperAdmin::class)) {
            abort(403);
        }

        $request->validate([
            'playerName',
            'countryName'
        ]);




        $superAdmin=SuperAdmin::find($id);
        $superAdmin->playerName=$request->get('playerName');
        $superAdmin->countryName=$request->get('countryName');
        $superAdmin->save();
        return redirect()->route('superAdmin.index')->with('success', 'Super Admin saved');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
  public function destroy($id)
    {
        //
        $superAdmin =SuperAdmin::find($id);
        $superAdmin ->delete($id);
        return redirect()->route('superAdmin.index')->with('success','Super Admin Deleted');
    }
}

resources/views/superAdmin/create.blade.php
@extends('home')
@section('homecontent')
<div class="row"> 
    <div class="col-sm-8 offset-sm-2">    
        <h3 class="display-4">Add </h3>  
        <div>    
            @if ($errors->any())      
            <div class="alert alert-danger">        
                <ul>            
                @foreach ($errors->all() as $error)              
                <li>{{ $error }}</li>            
                @endforeach        
                </ul>      
            </div>
            <br />    
            @endif  

            <form enctype="multipart/form-data" method="post" action="{{ route('superAdmin.store') }}">          
            @csrf 
          
                
            
             
            <div class="form-group d-flex flex-column">                  
                <label for="playerName">Player Name:</label>          
                <input type="text"  name="playerName"/>  
                       
            </div> 
            
            
           
           
            <div class="form-group">
                <label for="countryName">Select Country</label>
                <select id="country-select" class="selectpicker countrypicker" name='countryName'data-flag="true" ></select>
               
                
  
            </div>
                  
                           
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('superAdmin.index') }}" class="btn btn-primary">Cancel</a>  
                
            </form>  
        </div>
    </div>
</div>
@endsection

resources/views/superAdmin/edit.blade.php
@extends('home')
@section('homecontent')
<div class="row">    
    <div class="col-sm-8 offset-sm-2">        
        <h3 class="display-4">Update </h3>        
        @if ($errors->any())        
        <div class="alert alert-danger">            
            <ul>                
            @foreach ($errors->all() as $error)                
            <li>{{ $error }}</li>                
            @endforeach            
            </ul>        
        </div>        
        <br />         
        @endif        
        <form enctype="multipart/form-data" method="post" action="{{ route('superAdmin.update',$superAdmin->id) }}">            
        @method('PATCH')             
        @csrf  

            
            <div class="form-group d-flex flex-column">                  
                <label for="playerName">Player Name:</label>          
                <input type="text"  name="playerName" value='{{$superAdmin->playerName}}'/>  
                       
            </div> 
           
            
            <div class="form-group">
                <label for="countryName">Select Country</label>
                <select id="country-select" class="selectpicker countrypicker" name='countryName' data-flag="true" ></select>
                <script>
              
                $(document).ready(function() {
                    $('#country-select').val('{{$superAdmin->countryName}}');
                });

                        </script>
               
            </div>
           
                  
           

            <button type="submit" class="btn btn-success">Update</button>        
          <a href="{{ route('superAdmin.index') }}" class="btn btn-primary">Cancel</a>                        
        </form>
    </div>
</div>
@endsection

resources/views/superAdmin/index.blade.php
@extends('home')
@section('homecontent')

<div class="row">
    <div class="col-sm-12">    
        <h1 class="display-4">Super Admin</h1>   
        <a href="{{ route('superAdmin.create') }}" class="btn btn-primary">add</a>  
        <table class="table table-striped">    
            <thead>        
            <tr>          
                
                <td>Player Name</td>
                <td>Country Name</td>
               
                
               

                <td colspan = 2>Actions</td>        
            </tr>    
            </thead>    
            <tbody>        
                @foreach($superAdmins as $superAdmin)        
                    <tr>            
                       
                        <td>{{$superAdmin->playerName}}</td>
                        <td>{{$superAdmin->countryName}}
                        <!-- <?php 
                            // echo locale_get_display_region('$superAdmin', 'en');
                            ?> -->
                        </td>
                        
                    
              
                        
                        
                        <td>                                      
                            <a href="{{ route('superAdmin.edit',$superAdmin->id)}}" class="btn btn-primary">Edit </a>
                                                                  

                        </td> 
                        
                        
                        
                        <td>
                          <form action="{{ route('superAdmin.destroy',$superAdmin->id)}}" method="post">                  
                                @csrf                  
                               @method('DELETE')                  
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>    
                                      
                        </td> 
                        
          
                        
                    </tr>  

                @endforeach    
            </tbody>  
        </table>
       
    <div>
    
</div>


@endsection