routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Match;
use App\Models\SliderModel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // $sliders= \File::allFiles(public_path('images'));
    $sliders=SliderModel::all();
    $matches = Match::all();
    return view('welcome', compact('sliders','matches'));
    
 
});


Auth::routes();


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('superAdmin','App\Http\Controllers\superAdminController');
Route::resource('match','App\Http\Controllers\MatchController');
Route::resource('slider','App\Http\Controllers\SliderController');

app/Models/Match.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Match extends Model
{
    use HasFactory;
    public $table = 'match_scores';
    protected $fillable = [
        'country1',
        'country2',
        'date_time'

       
    ];
}

app/Http/Controllers/MatchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Match;

class MatchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $match = Match::all();
             
        return view('match.index', compact('match'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $match=Match::all();
        return view('match.create', compact('match'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        

        $request->validate([
           
            'country1',
            'country2',
            'date_time'
        ]);
        $match=new Match([
            'country1'=>$request->get('country1'),
            'country2'=>$request->get('country2'),
            'date_time'=>$request->get('date_time')

        ]);
        $match->save();
        return redirect()->route('match.index')->with('success','match saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $match=Match::find($id);
        return view('match.edit', compact('match'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
       
        $request->validate([
           
            'country1',
            'country2',
            'date_time'
        ]);



        $match=Match::find($id);
        $match->country1=$request->get('country1');
        $match->country2=$request->get('countryName');
        $match->date_time=$request->get('date_time');

        $match->save();
        return redirect()->route('match.index')->with('success', 'match saved');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $match =Match::find($id);
        $match ->delete($id);
        return redirect()->route('match.index')->with('success','matchDeleted');
    }
}

resources/views/match/create.blade.php
@extends('home')
@section('homecontent')

    
<div class="row"> 
<thead>  

            </thead> 
            
    <div class="col-sm-8 offset-sm-2">    
        <h3 class="display-4">Add </h3>  
        <div>    
            @if ($errors->any())      
            <div class="alert alert-danger">        
                <ul>            
                @foreach ($errors->all() as $error)              
                <li>{{ $error }}</li>            
                @endforeach        
                </ul>      
            </div>
            <br />    
            @endif  

            <form enctype="multipart/form-data" method="post" action="{{ route('match.store') }}">          
            @csrf 
          
              
            <div class="form-group">
            <label for="country1">Country A:</label>          
                <input type="text"  name="country1" /> 
                </div>
            
               
                
            <div class="form-group">                   
            <label for="date_time">Game Time:</label>
                <input type="datetime-local" name="date_time">         
            </div>   
  
            </div>
            <div class="form-group">
            <label for="country2">Country B:</label>          
                <input type="text"  name="country2" /> 
                </div>
               
               

           

            
            
           
           
            
                           
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('match.index') }}" class="btn btn-primary">Cancel</a>  
                
            </form>  
        </div>
    </div>
</div>
@endsection

resources/views/match/edit.blade.php
@extends('home')
@section('homecontent')
<div class="row">    
    <div class="col-sm-8 offset-sm-2">        
        <h3 class="display-4">Update </h3>        
        @if ($errors->any())        
        <div class="alert alert-danger">            
            <ul>                
            @foreach ($errors->all() as $error)                
            <li>{{ $error }}</li>                
            @endforeach            
            </ul>        
        </div>        
        <br />         
        @endif        
        <form enctype="multipart/form-data" method="post" action="{{ route('match.update',$match->id) }}">            
        @method('PATCH')             
        @csrf  

            
                           
            <div class="form-group">
            <label for="country1">Country A:</label>          
                <input type="text"  name="country1" value='{{$match->country1}}'/> 
                </div>   
          
           
            <div class="form-group">                   
            <label for="date_time">Game Time:</label>
                <input type="datetime-local" name="date_time">         
            </div>
            <div class="form-group">
            <label for="country2">Country B:</label>          
                <input type="text"  name="country2" value='{{$match->country2}}'/> 
                </div>
            </div>
           

           
                  
           

            <button type="submit" class="btn btn-success">Update</button>        
          <a href="{{ route('match.index') }}" class="btn btn-primary">Cancel</a>                        
        </form>
    </div>
</div>
@endsection

resources/views/match/index.blade.php
@extends('home')
@section('homecontent')
<div class="container">
<div class="row">
<h2> Game Time</h2>
    <div class="col-md-12">    
          
        <a href="{{ route('match.create') }}" class="btn btn-primary">add</a>  
        <table class="table table-striped">    
            <thead>        
            <tr> 
                 
                
                <td>Country A</td>
                <td>VS</td>
                <td>Country B</td>

                <td colspan = 2>Actions</td>        
            </tr>    
            </thead>    
            <tbody>        
                @foreach($match as $match)        
                    <tr>            
                   
                        <td>{{$match->country1}}</td>
                      


                      <td>{{$match->date_time}}</td> 

                      
                        <td>{{$match->country2}}</td>
                    
                        <td>                                      
                            <a href="{{ route('match.edit',$match->id)}}" class="btn btn-primary">Edit </a>
                                                                  

                        </td> 
                       
                        <td>
                          <form action="{{ route('match.destroy',$match->id)}}" method="post">                  
                                @csrf                  
                               @method('DELETE')                  
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>    
                                      
                        </td> 
                        
          
                        
                    </tr>  

                @endforeach    
            </tbody>  
        </table>
       
    <div>
    
</div>
</div>


@endsection